use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

/// Proposed research plan generated by the LLM.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct ResearchPlan {
    /// User ID requesting the research.
    pub user_id: Option<String>,
    /// Questions or objectives to be addressed.
    pub goals: Vec<String>,
    /// Domains intended to be visited.
    pub candidate_domains: Vec<String>,
    /// Maximum number of pages to crawl.
    pub max_pages: u32,
    /// Whether to follow cross-domain redirects.
    pub allow_redirects: bool,
    /// Estimated token budget.
    pub budget_tokens: Option<u32>,
}

/// A citation in the final research report.
#[derive(Debug, Clone, Serialize, Deserialize, JsonSchema)]
pub struct Citation {
    /// Source URL.
    pub url: String,
    /// The specific snippet or content hash.
    pub hash: String,
    /// Brief context or title.
    pub context: String,
}
